github:
  client_id: <client_id>
  client_secret: <client_secret>
  username: null
  password: null
irc:
  nick: <irc_nick>
  server: <server>
  port: 6667
  password: <server_password>
email:
  address: <address>
  password: <password>
 