github:
  repositories:
    -
      organization: <organization>
      name: <repository_name>
      reviewers:
        - # Level 1
          - <github_login>
          - <github_login>
          - ...
        - # Level 2
          - ...
        - ...
      maintainers:
        - <github_login>
        - ...
events:
  check_every: 60  # Checks for new event every X seconds
  buffer_length: 100000  # Keep X events back
logging_level: INFO  # Available levels are described here: https://docs.python.org/3/library/logging.html#levels
database:
  mongo_client:
    host: <host>
    port: <port>
